export const categories = [
  { name: 'Классика' },
  { name: 'Кэжуал' },
  { name: 'Спорт' },
  { name: 'Винтаж' }
];

export const brands = [
  { name: 'Louis Vuitton' },
  { name: 'Gucci' },
  { name: 'Chanel' },
  { name: 'Prada' },
  { name: 'Dior' },
  { name: 'Burberry' },
  { name: 'Versace' },
  { name: 'Givenchy' },
  { name: 'Balenciaga' },
  { name: 'Fendi' },
  { name: 'Saint Laurent' },
  { name: 'Alexander McQueen' },
  { name: 'Valentino' },
  { name: 'Hermès' },
  { name: 'Armani' },
  { name: 'Tom Ford' },
  { name: 'Bottega Veneta' },
  { name: 'Salvatore Ferragamo' },
  { name: 'Stella McCartney' },
  { name: 'Celine' }
];

export const colors = [
  'Чёрный',
  'Белый',
  'Красный',
  'Жёлтый',
  'Зелёный',
  'Синий',
  'Голубой',
  'Коричневый',
  'Серый',
  'Фиолетовый',
  'Розовый',
  'Оранжевый',
  'Бордовый',
  'Бежевый',
  'Бирюзовый',
  'Малиновый',
  'Изумрудный',
  'Хаки',
  'Лаймовый',
  'Песочный'
];

export const sizes = [
 'S', 'M', 'L', 'XL', 'XXL', '3XL', '4XL',
];

export const types = [
  'Брюки',
  'Шорты',
  'Джинсы',
  'Юбка',
  'Платье',
  'Рубашка',
  'Футболка',
  'Майка',
  'Свитер',
  'Кардиган',
  'Жакет',
  'Пальто',
  'Куртка',
  'Пуховик',
  'Ветровка',
  'Костюм',
  'Комбинезон',
  'Худи',
  'Поло',
  'Толстовка',
  'Леггинсы',
  'Пижама',
  'Ночная рубашка',
  'Сарафан',
  'Блузка',
  'Водолазка'
];

export const products = [
  {
      name: 'Prada Белое платье‑рубашка',
      description: 'Платье‑рубашка свободного кроя, выполнено из лёгкого шёлкового хлопка, с длинными рукавами.',
      composition: '95% хлопок, 5% эластан',
      price: 12500,
      imageUrl: 'https://project-files.picsart.com/project_files/a3f38226-be5d-4af0-9977-b1b9e60ca649.png',
      categoryId: 1,
      typeId: 5,
      brandId: 4,
      colorId: 2,
      sizes: ['S', 'M', 'L', 'XL', 'XXL', '3XL', '4XL',]
  },
  {
      name: 'Chanel Черное классическое платье',
      description: 'Элегантное черное платье с V-образным вырезом и короткими рукавами. Прямой силуэт, универсальный дизайн для различных случаев.',
      composition: '70% Полиэстер, 25% Вискоза, 5% Эластан',
      price: 18500,
      imageUrl: 'https://project-files.picsart.com/project_files/91e89a6e-2c21-4c7a-b303-54b2662897bc.png',
      categoryId: 1,
      typeId: 5,
      brandId: 3,
      colorId: 1,
      sizes: ['S', 'M', 'L', 'XL', 'XXL', '3XL', '4XL',]
  },
  {
      name: 'Givenchy Черный укороченный жакет',
      description: 'Стильный укороченный жакет классического черного цвета с длинными рукавами, однобортной застежкой на одну пуговицу и острыми лацканами.',
      composition: '80% Полиэстер, 18% Вискоза, 2% Эластан',
      price: 21000,
      imageUrl: 'https://project-files.picsart.com/project_files/efd8aa0b-1a7c-4c6a-bf22-bf1d62503025.png',
      categoryId: 1,
      typeId: 11,
      brandId: 8,
      colorId: 1,
      sizes: ['S', 'M', 'L', 'XL', 'XXL', '3XL', '4XL',]
  },
  {
      name: 'Dior Черные широкие брюки со складками',
      description: 'Классические черные брюки с высокой посадкой и широкими штанинами. Декоративные складки у пояса спереди. Идеально подходят для создания элегантных образов.',
      composition: '70% Шерсть, 28% Полиэстер, 2% Эластан',
      price: 15000,
      imageUrl: 'https://project-files.picsart.com/project_files/45d51d6d-9fea-4844-a9cd-bb6abb2ab87f.png',
      categoryId: 1,
      typeId: 1,
      brandId: 5,
      colorId: 1,
      sizes: ['S', 'M', 'L', 'XL', 'XXL', '3XL', '4XL',]
  },
  {
      name: 'Dior Белая укороченная блузка с жемчужными пуговицами',
      description: 'Элегантная белая укороченная блузка в стиле жакета с двубортной застежкой на жемчужные пуговицы. Имеет широкие лацканы и объемные рукава с манжетами на резинке.',
      composition: '100% Полиэстер',
      price: 17500,
      imageUrl: 'https://project-files.picsart.com/project_files/76c5f506-1b07-4755-8442-b2c95d9ad7de.png',
      categoryId: 1,
      typeId: 25,
      brandId: 5,
      colorId: 2,
      sizes: ['S', 'M', 'L', 'XL', 'XXL', '3XL', '4XL',]
  },
  {
      name: 'Fendi Черные шорты с высокой талией',
      description: 'Классические черные шорты с высокой посадкой и защипами спереди. Прямой крой, застежка на молнию и пуговицу. Элегантный вариант для летнего гардероба.',
      composition: '60% Полиэстер, 35% Вискоза, 5% Эластан',
      price: 11000,
      imageUrl: 'https://project-files.picsart.com/project_files/e013b423-2a6e-483d-a847-870bbe210651.png',
      categoryId: 1,
      typeId: 2,
      brandId: 10,
      colorId: 1,
      sizes: ['S', 'M', 'L', 'XL', 'XXL', '3XL', '4XL',]
  },
  {
      name: 'Stella McCartney Черно-белый укороченный топ с объемными рукавами',
      description: 'Стильный укороченный топ комбинированного дизайна: черная основа-бандо с объемными белыми рукавами и отложным воротником, формирующим V-образный вырез.',
      composition: '90% Хлопок, 10% Эластан',
      price: 22000,
      imageUrl: 'https://project-files.picsart.com/project_files/bbda3654-7fde-4fc2-8f1e-e7279b90cfb2.png',
      categoryId: 2,
      typeId: 25,
      brandId: 19,
      colorId: 1,
      sizes: ['S', 'M', 'L', 'XL', 'XXL', '3XL', '4XL',]
  },
  {
      name: 'Tom Ford Черное атласное платье комбинация',
      description: 'Изысканное черное платье-комбинация из струящегося атласа с V-образным вырезом и тонкими бретелями. Минималистичный силуэт, идеально подходит для вечерних выходов.',
      composition: '95% Полиэстер, 5% Эластан',
      price: 28000,
      imageUrl: 'https://project-files.picsart.com/project_files/4869b465-c11d-467a-bb33-3ee0224b9965.png',
      categoryId: 1,
      typeId: 5,
      brandId: 16,
      colorId: 1,
      sizes: ['S', 'M', 'L', 'XL', 'XXL', '3XL', '4XL',]
  },
  {
      name: 'Valentino Бежевый укороченный топ-бюстье с баской',
      description: 'Элегантный укороченный топ-бюстье бежевого цвета без бретелей. Особенности: V-образный вырез, декоративный перекрученный элемент на лифе и расклешенная баска по низу.',
      composition: '92% Полиэстер, 8% Эластан',
      price: 26000,
      imageUrl: 'https://project-files.picsart.com/project_files/ba10f7e8-0db2-4632-a251-68eb8a25b749.png',
      categoryId: 1,
      typeId: 25,
      brandId: 13,
      colorId: 14,
      sizes: ['S', 'M', 'L', 'XL', 'XXL', '3XL', '4XL',]
  },
  {
      name: 'Versace Бежевый атласный топ-бандо',
      description: 'Изысканный бежевый топ-бандо без бретелей с декоративной драпировкой и перекрученным элементом спереди. Выполнен из гладкого атласного материала.',
      composition: '95% Полиэстер, 5% Эластан',
      price: 24000,
      imageUrl: 'https://project-files.picsart.com/project_files/ad2c47a7-a6ee-41b2-9e40-03fa42197434.png',
      categoryId: 1,
      typeId: 25,
      brandId: 7,
      colorId: 14,
      sizes: ['S', 'M', 'L', 'XL', 'XXL', '3XL', '4XL',]
  },
  {
      name: 'Balenciaga Серый джинсовый топ-корсет',
      description: 'Стильный укороченный джинсовый топ-корсет с тонкими бретелями и формирующими швами. Выполнен из выбеленного серого денима. Акцентная деталь для кэжуал образа.',
      composition: '98% Хлопок, 2% Эластан',
      price: 14000,
      imageUrl: 'https://project-files.picsart.com/project_files/4f4273d5-198b-475f-a811-9a3b80dcbb46.png',
      categoryId: 2,
      typeId: 8,
      brandId: 9,
      colorId: 9,
      sizes: ['S', 'M', 'L', 'XL', 'XXL', '3XL', '4XL',]
  },
  {
      name: 'Versace Черная кожаная куртка-косуха',
      description: 'Классическая черная куртка-косуха из искусственной кожи с асимметричной молнией, широкими лацканами на кнопках и декоративными карманами на молнии. Дополнена поясом по низу.',
      composition: '60% Полиуретан, 40% Полиэстер',
      price: 23000,
      imageUrl: 'https://project-files.picsart.com/project_files/60cd20b5-a483-4773-ae99-7ec2e8ad1e00.png',
      categoryId: 2,
      typeId: 13,
      brandId: 7,
      colorId: 1,
      sizes: ['S', 'M', 'L', 'XL', 'XXL', '3XL', '4XL',]
  },
  {
      name: 'Celine Белая майка в рубчик',
      description: 'Базовая облегающая майка белого цвета в мелкий рубчик с округлым вырезом горловины и узкими бретелями. Незаменимая вещь для повседневных образов.',
      composition: '95% Хлопок, 5% Эластан',
      price: 9500,
      imageUrl: 'https://project-files.picsart.com/project_files/11977c2e-cf26-434a-9686-b13e8f51205c.png',
      categoryId: 2,
      typeId: 8,
      brandId: 20,
      colorId: 2,
      sizes: ['S', 'M', 'L', 'XL', 'XXL', '3XL', '4XL',]
  },
  {
      name: 'Armani Белая водолазка с высоким горлом и драпировкой',
      description: 'Элегантный белая облегающая водолазка с высоким воротом и длинными рукавами. Изящная драпировка на талии создает эффектный акцент.',
      composition: '90% Вискоза, 10% Эластан',
      price: 13500,
      imageUrl: 'https://project-files.picsart.com/project_files/eba4878c-5e86-402f-8d0d-4279e64addd8.png',
      categoryId: 2,
      typeId: 26,
      brandId: 15,
      colorId: 2,
      sizes: ['S', 'M', 'L', 'XL', 'XXL', '3XL', '4XL',]
  },
  {
      name: 'Gucci Белый лонгслив оверсайз',
      description: 'Классический базовый лонгслив свободного кроя (оверсайз) белого цвета с круглым вырезом горловины и длинными рукавами. Выполнен из мягкого плотного хлопка.',
      composition: '100% Хлопок',
      price: 16000,
      imageUrl: 'https://project-files.picsart.com/project_files/3e87151a-6b15-4a00-8658-7c67b2afa702.png',
      categoryId: 2,
      typeId: 7,
      brandId: 2,
      colorId: 2,
      sizes: ['S', 'M', 'L', 'XL', 'XXL', '3XL', '4XL',]
  },
  {
      name: 'Celine Бежевый свитер с отложным воротником',
      description: 'Вязаный свитер прямого кроя из мягкой шерсти с добавлением кашемира. Модель выполнена в бежевом цвете с отложным воротником поло и рукавами реглан.',
      composition: '80% Шерсть, 20% Кашемир',
      price: 22000,
      imageUrl: 'https://project-files.picsart.com/project_files/9c619a45-646c-4335-9338-8a15eb57ee71.png',
      categoryId: 2,
      typeId: 9,
      brandId: 20,
      colorId: 14,
      sizes: ['S', 'M', 'L', 'XL', 'XXL', '3XL', '4XL',]
  },
  {
      name: 'Burberry Черно-бежевый свитер в клетку',
      description: 'Уютный вязаный свитер прямого кроя с круглым вырезом горловины и длинными рукавами. Выполнен в контрастном черно-бежевом шахматном узоре.',
      composition: '50% Акрил, 30% Нейлон, 20% Шерсть',
      price: 18000,
      imageUrl: 'https://project-files.picsart.com/project_files/e552ec1a-e3ff-42ee-9a94-6a919d37d73f.png',
      categoryId: 2,
      typeId: 9,
      brandId: 6,
      colorId: 14,
      sizes: ['S', 'M', 'L', 'XL', 'XXL', '3XL', '4XL',]
  },
  {
      name: 'Chanel Серый клетчатый жакет',
      description: 'Жакет в черно-серую клетку. Однобортная модель с лацканами и застежкой на пуговицу.',
      composition: '50% Шерсть, 45% Полиэстер, 5% Акрил',
      price: 20000,
      imageUrl: 'https://project-files.picsart.com/project_files/7f1e289d-8c1c-464a-8231-78ac81ba0655.png',
      categoryId: 2,
      typeId: 11,
      brandId: 3,
      colorId: 9,
      sizes: ['S', 'M', 'L', 'XL', 'XXL', '3XL', '4XL',]
  },
  {
      name: 'Burberry Черная спортивная ветровка с полосками',
      description: 'Черная спортивная ветровка с воротником-стойкой и застежкой на молнию. Украшена контрастными белыми полосками в форме шеврона на груди и рукавах. Манжеты и низ на резинке.',
      composition: '100% Полиэстер',
      price: 15000,
      imageUrl: 'https://project-files.picsart.com/project_files/978e3c88-ed23-4ccd-b277-49bf445c4508.png',
      categoryId: 3,
      typeId: 15,
      brandId: 6,
      colorId: 1,
      sizes: ['S', 'M', 'L', 'XL', 'XXL', '3XL', '4XL',]
  },
  {
      name: 'Burberry Черный кроп-топ с серыми рукавами',
      description: 'Стильный укороченный топ в спортивном стиле с контрастными серыми рукавами реглан и круглым вырезом горловины. Изготовлен из мягкого трикотажа.',
      composition: '95% Хлопок, 5% Полиэстер',
      price: 10000,
      imageUrl: 'https://project-files.picsart.com/project_files/b2eb53f1-296b-4d5c-88bf-41cf09928d44.png',
      categoryId: 3,
      typeId: 7,
      brandId: 6,
      colorId: 1,
      sizes: ['S', 'M', 'L', 'XL', 'XXL', '3XL', '4XL',]
  },
  {
      name: 'Burberry Белая спортивная ветровка с кантом',
      description: 'Легкая спортивная ветровка белого цвета с воротником-стойкой и застежкой на пуговицы. Декорирована тонкими контрастными полосками (кантом) вдоль рукавов реглан.',
      composition: '70% Полиэстер, 30% Хлопок',
      price: 12000,
      imageUrl: 'https://project-files.picsart.com/project_files/97e93e0b-8d40-47a8-bec2-d314745f9d84.png',
      categoryId: 3,
      typeId: 15,
      brandId: 6,
      colorId: 2,
      sizes: ['S', 'M', 'L', 'XL', 'XXL', '3XL', '4XL',]
  },
  {
      name: 'Salvatore Ferragamo Черный комбинезон с V-образным вырезом',
      description: 'Облегающий комбинезон черного цвета с короткими рукавами и широким отложным воротником, образующим глубокий V-образный вырез.',
      composition: '95% Хлопок, 5% Эластан',
      price: 15000,
      imageUrl: 'https://project-files.picsart.com/project_files/8b84736d-9da3-4d69-a33c-efb0b9ece36f.png',
      categoryId: 3,
      typeId: 17,
      brandId: 18,
      colorId: 1,
      sizes: ['S', 'M', 'L', 'XL', 'XXL', '3XL', '4XL',]
  },
  {
      name: 'Prada Черное поло с контрастным воротником',
      description: 'Облегающее поло черного цвета из трикотажа в рубчик с короткими рукавами. Модель с контрастным белым отложным воротником, формирующим V-образный вырез.',
      composition: '80% Вискоза, 15% Нейлон, 5% Эластан',
      price: 14000,
      imageUrl: 'https://project-files.picsart.com/project_files/dd03b9d4-3869-4d33-88cf-0236f94af910.png',
      categoryId: 3,
      typeId: 19,
      brandId: 4,
      colorId: 1,
      sizes: ['S', 'M', 'L', 'XL', 'XXL', '3XL', '4XL',]
  },
  {
      name: 'Balenciaga Черная толстовка оверсайз',
      description: 'Базовая толстовка свободного кроя (оверсайз) черного цвета с круглым вырезом горловины и длинными рукавами. Манжеты и низ изделия на резинке.',
      composition: '80% Хлопок, 20% Полиэстер',
      price: 11000,
      imageUrl: 'https://project-files.picsart.com/project_files/dd8ee14c-2b04-4c02-8e51-4f1d1025c1cb.png',
      categoryId: 3,
      typeId: 20,
      brandId: 9,
      colorId: 1,
      sizes: ['S', 'M', 'L', 'XL', 'XXL', '3XL', '4XL',]
  },
  {
      name: 'Prada Черная облегающая футболка',
      description: 'Облегающая черная футболка с короткими рукавами и круглым вырезом горловины. Базовая модель приталенного силуэта из эластичного трикотажа.',
      composition: '95% Хлопок, 5% Эластан',
      price: 9800,
      imageUrl: 'https://project-files.picsart.com/project_files/cac26acf-1351-476e-8654-84eaa064b010.png',
      categoryId: 3,
      typeId: 7,
      brandId: 4,
      colorId: 1,
      sizes: ['S', 'M', 'L', 'XL', 'XXL', '3XL', '4XL',]
  },
  {
      name: 'Balenciaga Серый худи оверсайз',
      description: 'Удобный худи свободного кроя (оверсайз) серого цвета с капюшоном и длинными рукавами. Базовая модель из мягкого футера.',
      composition: '80% Хлопок, 20% Полиэстер',
      price: 12000,
      imageUrl: 'https://project-files.picsart.com/project_files/ee81f72e-60d4-4f8c-8e48-4dc19b825469.png',
      categoryId: 3,
      typeId: 18,
      brandId: 9,
      colorId: 9,
      sizes: ['S', 'M', 'L', 'XL', 'XXL', '3XL', '4XL',]
  },
  {
      name: 'Balenciaga Серые спортивные брюки',
      description: 'Удобные спортивные брюки (джоггеры) серого цвета. Модель с эластичным поясом на кулиске со шнурком и манжетами на щиколотках.',
      composition: '80% Хлопок, 20% Полиэстер',
      price: 12000,
      imageUrl: 'https://project-files.picsart.com/project_files/54297fb2-e52e-486f-b859-02069a3da529.png',
      categoryId: 3,
      typeId: 1,
      brandId: 9,
      colorId: 9,
      sizes: ['S', 'M', 'L', 'XL', 'XXL', '3XL', '4XL',]
  },
  {
      name: 'Givenchy Черно-белый кардиган в ромб',
      description: 'Уютный вязаный кардиган с классическим узором "аргайл" в черно-белой гамме. Модель с V-образным вырезом и застежкой на пуговицы. Идеален для создания винтажных и кэжуал образов.',
      composition: '50% Акрил, 50% Шерсть',
      price: 19000,
      imageUrl: 'https://project-files.picsart.com/project_files/7ccf9953-3589-4748-a649-f6455811e352.png',
      categoryId: 4,
      typeId: 9,
      brandId: 8,
      colorId: 1,
      sizes: ['S', 'M', 'L', 'XL', 'XXL', '3XL', '4XL',]
  },
  {
      name: 'Gucci Белая блузка с рюшами',
      description: 'Изящная белая блузка с длинными рукавами и объемными рюшами вдоль V-образного выреза. Имеет классический воротник и собранные манжеты.',
      composition: '100% Полиэстер',
      price: 19500,
      imageUrl: 'https://project-files.picsart.com/project_files/e6dca5ee-fe3e-40da-82c2-bd6af37f230f.png',
      categoryId: 4,
      typeId: 25,
      brandId: 2,
      colorId: 2,
      sizes: ['S', 'M', 'L', 'XL', 'XXL', '3XL', '4XL',]
  },
  {
      name: 'Dior Черный твидовый жакет с золотыми пуговицами',
      description: 'Классический укороченный твидовый жакет черного цвета с круглым вырезом и длинными рукавами. Декорирован золотыми пуговицами и накладными карманами.',
      composition: '55% Шерсть, 30% Полиэстер, 15% Акрил',
      price: 27000,
      imageUrl: 'https://project-files.picsart.com/project_files/11eed50b-8690-4de4-85e4-699163bdf168.png',
      categoryId: 4,
      typeId: 11,
      brandId: 5,
      colorId: 1,
      sizes: ['S', 'M', 'L', 'XL', 'XXL', '3XL', '4XL',]
  },
  {
      name: 'Givenchy Черная многоярусная мини-юбка с бантами',
      description: 'Короткая черная юбка с высокой эластичной (смокинг) талией и несколькими ярусами воланов. Декорирована маленькими атласными бантами спереди на поясе.',
      composition: '100% Полиэстер',
      price: 14000,
      imageUrl: 'https://project-files.picsart.com/project_files/5ca1e5a1-e175-46d6-bf4d-dbd8b3d1b16d.png',
      categoryId: 4,
      typeId: 4,
      brandId: 8,
      colorId: 1,
      sizes: ['S', 'M', 'L', 'XL', 'XXL', '3XL', '4XL',]
  },
  {
      name: 'Versace Черная асимметричная юбка с драпировкой',
      description: 'Стильная черная мини-юбка с высокой посадкой, эластичной драпировкой по бокам и асимметричным подолом. Декорирована шнурками-завязками.',
      composition: '100% Полиэстер',
      price: 16000,
      imageUrl: 'https://project-files.picsart.com/project_files/6d80dad5-4993-4fb8-81f6-a107c36f79bf.png',
      categoryId: 4,
      typeId: 4,
      brandId: 7,
      colorId: 1,
      sizes: ['S', 'M', 'L', 'XL', 'XXL', '3XL', '4XL',]
  },
  {
      name: 'Givenchy Черный кожаный жакет',
      description: 'Элегантный винтажный жакет из искусственной кожи черного цвета. Однобортная модель с лацканами, застежкой на одну пуговицу и нагрудным карманом. Свободный крой.',
      composition: '50% Полиуретан, 50% Полиэстер',
      price: 24000,
      imageUrl: 'https://project-files.picsart.com/project_files/35b7d050-1396-4897-bdd6-0ca2e249936d.png',
      categoryId: 4,
      typeId: 11,
      brandId: 8,
      colorId: 1,
      sizes: ['S', 'M', 'L', 'XL', 'XXL', '3XL', '4XL',]
  },
  {
      name: 'Valentino Черный кружевной топ-бралетт',
      description: 'Изысканный черный кружевной топ-бралетт с V-образным вырезом и тонкими бретелями. Декорирован маленьким бантом спереди.',
      composition: '90% Нейлон, 10% Эластан',
      price: 10000,
      imageUrl: 'https://project-files.picsart.com/project_files/bd803421-4869-4c4d-a169-d7f942b36704.png',
      categoryId: 4,
      typeId: 8,
      brandId: 13,
      colorId: 1,
      sizes: ['S', 'M', 'L', 'XL', 'XXL', '3XL', '4XL',]
  },
  {
      name: 'Gucci Черная кружевная блузка с высоким горлом',
      description: 'Элегантная облегающая блузка из полупрозрачного черного кружева с цветочным узором. Высокий воротник-стойка с рюшами и длинные рукава.',
      composition: '90% Полиэстер, 10% Нейлон',
      price: 29000,
      imageUrl: 'https://project-files.picsart.com/project_files/cf67c8ea-5dcc-4986-b9e7-1e98a1740d1c.png',
      categoryId: 4,
      typeId: 25,
      brandId: 2,
      colorId: 1,
      sizes: ['S', 'M', 'L', 'XL', 'XXL', '3XL', '4XL',]
  },
  {
      name: 'Chanel Черный трикотажный топ с бантом',
      description: 'Черный укороченный топ из эластичного трикотажа в рубчик. Модель на тонких бретелях с декоративным бантом спереди.',
      composition: '95% Хлопок, 5% Эластан',
      price: 9000,
      imageUrl: 'https://project-files.picsart.com/project_files/727b188c-8f92-4d28-bf28-4e01182b815d.png',
      categoryId: 4,
      typeId: 8,
      brandId: 3,
      colorId: 1,
      sizes: ['S', 'M', 'L', 'XL', 'XXL', '3XL', '4XL',]
  }
];
